### ISSUE TITLE
Not deleting

### ISSUE THREAD

**Issue by KevinDenys** [verticelo/fb-groups-delete-posts-older-than-x-days#1]
Listing works, showing posts older than x days works but deleting them doesnt

**Comment by verticelo** [comment]
- Are you the administrator in the group?
- What response do you get from FB using DevTools or something else?

I just used it the other day to delete a bunch of posts and it worked well.

**Comment by KevinDenys** [comment]
1. I am yes
2. How you mean?

It deleted the group picture, but not the shared links people posted

**Comment by verticelo** [comment]
Did you figure out the issue? If so, what was it?

Group pictures are deleted because it is a post unfortunately. Probably possible to filter and find out which post that is and exclude it for deletion.
